# Generated by Django 5.1.4 on 2025-06-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, choices=[('TeamLead', 'Team Lead'), ('TEAM1', 'Team 1'), ('TEAM2', 'Team 2'), ('TEAM3', 'Team 3'), ('TEAM4', 'Team 4'), ('TEAM5', 'Team 5'), ('TEAM6', 'Team 6'), ('TEAM7', 'Team 7'), ('TEAM8', 'Team 8'), ('TEAM9', 'Team 9'), ('TEAM10', 'Team 10'), ('Support', 'Support Team')], default='Team 0', max_length=20, null=True),
        ),
    ]
