# Generated by Django 5.1.4 on 2025-01-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.CharField(blank=True, choices=[('TeamLead', 'Team Lead'), ('TEAM1', 'Team 1'), ('TEAM2', 'Team 2'), ('TEAM3', 'Team 3'), ('TEAM4', 'Team 4'), ('TEAM5', 'Team 5')], default='Team 0', max_length=20, null=True),
        ),
    ]
