# Generated by Django 5.1.4 on 2025-01-14 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'SUPERVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
